Change leaderboard font and size
Foohy/jazztronauts pull request #172
Opened 2023-05-25 14:01 UTC by Commenter25

Closes #118

I think KG Red Hands fits great for this: It's big and bold like Impact, fits naturally into the aesthetic, and happens to be the same creator as another font here!

This kinda broke the sizing of things, so I also took this opportunity to make the leaderboard far bigger and more readable.

I think the leaderboard can be expanded to the top 10 players, but just changing `BoardEntryCount` in `jazzboards.lua` didn't seem to work (at least attempting to test with bot_mimic and pulling the lever over and over), so I'll leave that for a later PR if this is merged.

<details>

<summary>Comparison images (3MB)</summary>

Apologies for the awful quality, I do my development on a craptop... but the low resolution also highlights how unreadable the small size can be.

**Before:**
![Front view of the leaderboard before this PR](https://github.com/Foohy/jazztronauts/assets/35016761/5c9ad7bf-7835-4d2e-8d8f-69caa63e4840)

**After:**
![Front view of the leaderboard after this PR](https://github.com/Foohy/jazztronauts/assets/35016761/72adc508-1fbe-4527-9a81-71844a3a830d)

</details>

2023-05-26 17:38 UTC, SageJFox requested changes
Remove the vmf change (I'll put it in my updated copy) and the position fix, and should be good to go (so long as other folks like the style, I think it looks good.)

2023-05-27 00:14 UTC, Commenter25 commented
I did a quick check to make sure it still looks fine with the default font, and it does, so that should be fine! Thank you!!

2023-05-27 14:45 UTC, SageJFox approved these changes

2023-05-29 04:40 UTC, Foohy commented
Looks great to me! Mergin' that in

2023-05-29 04:40 UTC, merged